### ISSUE TITLE
Improve dashboard setup documentation

### ISSUE THREAD

**Issue by Phoenix616** [dimaguy/ImpostorHQ#15]
Currently the information provided for setting this up are rather sparse which makes it near impossible to setup with Docker. Information about stuff like used directories and ports without having to go through the source code would be nice to have.

The stuff I found after some trial and error:

- Webinterface runs on port `22024`, web socket on `22023` so both of those need to be forwarded
- Folder `/app/configs` is used for config files
- Folder `/app/dashboard` is used for the dashboard files
- Folder `/app/hqplugins` is used for plugins
- If setting up SSL: Follow the SSL guide, if you only have PEMs (like from Let's Encrypt) [export them as pfx](https://opentechtips.com/create-and-export-a-lets-encrypt-wildcard-ssl-certificate-in-a-pfx-format/) and then forward `/app/antiHttps.pfx` to the created pfx file. (Would really be better to support PEMs for SSL though)

**Comment by dimaguy** [comment]
We never actually counted on docker installations(since they are quite inflexible by default), but I guess I could add some docs to the readme yes
About the ssl situation, it was hard enough to convince the dev behind it so I could add instructions for ACME SSL Certs(he wanted to rely only on self signed certs because we have our own encryption scheme) so I think PEM support is out of question
