### ISSUE TITLE
Disable Console Logging on Dashboard 

### ISSUE THREAD

**Issue by gavinsteinhoff** [dimaguy/ImpostorHQ#9]
The dashboard is logging many events, 2000 events in a few minutes. 

Is this an intended feature? 

![image](https://user-images.githubusercontent.com/10859074/100492989-1d81ca80-30f8-11eb-8075-36bda02c11da.png)

**Comment by dimaguy** [comment]
I mean it isnt supposed to be that much. I set those up for debugging purposes.

***ONMESSAGE-receiving the message and triggering the event
Message received: object- show the contents of the message
HEARTBEAT-it detected that it is a heartbeat and does everything related to it

I am going to set everything to console.debug or something like that so that we can reduce clutter

**Comment by dimaguy** [comment]
b41a2e68 should fix this issue. Ive moved repeated messages to debug and overall should improve over console logging.
I am going to leave this issue open for some time and if there are no further complaints I'm going to close it :)
Thanks for reporting this!
